### ISSUE TITLE
challenges completion command

### ISSUE THREAD

**Issue by DamageDoctor** [tastybento/askyblock#238]
Just wondering if there is any plan to allow challenges to be completed via a command rather than the GUI?

There is the ability to "pull" items out of the GUI into a players inventory allowing players to cheat items into the game using a particular key combination. If you are unaware of this then I am happy to share the key combination.

Adding a command line option for the GUI based items like biome change, challenges etc would be amazing and eliminate the problem.

**Comment by tastybento** [comment]
Please share the key combo and I'll see if it happens with only ASkyBlock installed. Usually if players can pull items then it's caused by another plugin 99% of the time. 
Challenges can be done via command line (try /c c <name of challenge>). It was like that originally but hidden from view. There is a lot of info now that would not be visible via command line. I don't want to go back.

**Comment by DamageDoctor** [comment]
With GUI open hold CTRL and SHIFT and then left click an item out of the GUI. It moves the item into player inventory.

**Comment by tastybento** [comment]
I can't replicate that. What other plugins are you running?

**Comment by DamageDoctor** [comment]
I am guessing it’s a 1.7.10 issue then and maybe fixed in later versions. I will do some testing and see if I can isolate that as the plugins list is quite long.

**Comment by Carisus** [comment]
I can confirm that you can get items out of the GUI using the key combination provided above. When in survival mode, at least with my testing, the items would disappear when clicked on. In creative mode they would persist, complete with the custom names. My admins have started to use it as a way to get everyone's player head (via the warp section).

**Comment by tastybento** [comment]
I'd like to make a list of plugins that cause this failure so I can stick it in the FAQ. I'll close this for now, but comments can still be added.

**Comment by vimes1984** [comment]
Here's one for your list: [Vault](https://dev.bukkit.org/bukkit-plugins/vault/)

**Comment by Carisus** [comment]
I have a clean (fresh Spigot build) server with no other plugins except ASkyBlock and Vault and the problem is still there.

**Comment by tastybento** [comment]
I've tried with Windows and Mac and cannot replicate it. What client are you using? Here's what I tried:

1. Use 1.10 vanilla client and 1.10.2 Spigot server (relatively recent, few versions old)
2. Log in
3. Do /challenges
4. Press CTL + SHIFT and left click on item
5. See item momentarily appear in inventory and then disappear again.

**Comment by Carisus** [comment]
I have tested on two separate systems, Windows and Linux. The same way on both.

1. 1.10.2 Spigot and Client. Spigot was built 10 - 15 minutes before the test.
2. Download latest for ASkyBlock on Spigot 10 - 15 minutes before test.
3. Log in
4. Open the GUI with /island
5. Press and hold CTL + SHIFT and left click on an item.
6. See item appear in inventory
If you are in Survival mode, clicking on the item will remove it.
In Creative mode clicking will attach it to your cursor.

This isn't a big deal for most items, since you can get them from the Creative menu anyway. But the default item for "[island] spawn" is bedrock.

**Comment by Carisus** [comment]
In gamemode 0, I have also tested filling up my inventory and leaving one slot open so that the item fills a hotbar position. Right clicking with the item in your hand does not place the item.

I think you may need to cancel the [shift_right ClickType](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/ClickType.html#SHIFT_RIGHT) somewhere in the ControlPanel.java to get this problem to go away.

**Comment by Steev93** [comment]
Following,

I also could replicate it, running version V3.0.1.1

**Comment by tastybento** [comment]
The comment is that you can keep the item if the player is in Creative, but not in Survival. Correct?

**Comment by Carisus** [comment]
Correct

**Comment by tastybento** [comment]
Hmm, the event is canceled no matter what happens, but I'll try some things and make a test build. I'm wondering if it's a race condition of some kind between the client and server. Thanks for the tips.

**Comment by tastybento** [comment]
Latest version has mitigation. Should be fixed now.
